### ISSUE TITLE
Moving parameter of a chosen element is restricted

### ISSUE THREAD

**Issue by jowoni** [CAU-OSS-2019/team-project-team9#53] opened 2019-06-01 11:01 UTC
Hello,

I tested your extension in the following link below.
https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&sug=&sugo=&q=%EC%84%9C%EC%9A%B8+%EB%82%A0%EC%94%A8

![webuffet2](https://user-images.githubusercontent.com/42177510/58747570-d8032380-84a7-11e9-8256-7b9d1a54948a.PNG)
![webuffet3](https://user-images.githubusercontent.com/42177510/58747567-d0dc1580-84a7-11e9-893e-4ce88a755c0a.PNG)

And as you can see the chosen element has a restricted moving parameter and cannot be seen outside that parameter.

I'm not sure if it's a bug or it's intended to work that way but, if possible, enabling the chosen element to move anywhere in the browser will definitely be a good feature for the project.

Thank you

**Comment by jhaemin** [comment] 2019-06-01 11:33
It happens because of a CSS property `overflow: hidden` applied to the selected element's parent elements.

We could make it work by just simply enabling the visibility of the wrapping elements. (see a screenshot below)

![Screen Shot 2019-06-01 at 8 17 18 PM](https://user-images.githubusercontent.com/19797697/58747733-4943d600-84aa-11e9-8189-b58e7d59a057.png)

However, it may produce the unexpected and harmful behaviour throughout the overall website's default UI and UX. Although WEBuffet is meant to be able to manipulate the websites as your taste, it should only affect the selected elements by the users. At worst, it may destruct the whole view structure of the page (luckily not for the given url).

In the same context, a translated element may not be shown under the other elements that have higher z-indexes.

For now, we would keep obeying the HTML box-model hierarchy and the original overflow visibility.

I'm going to specify more details about this inside the README.

Thanks for your issue report.

**Comment by jhaemin** [comment] 2019-06-01 11:35
I close this issue because it's not a bug.

**Closed as completed by jhaemin** 2019-06-01 11:35 UTC
